### ISSUE TITLE
weights files

### ISSUE THREAD

**Issue by AllenPeng-libra** [SCccc21/Knowledge-Enriched-DMI#2]
could you please share the following 2 model weights files?
if args.improved_flag == True:
    D = MinibatchDiscriminator()
    path_G = './improvedGAN/improved_celeba_G.tar'
    path_D = './improvedGAN/improved_celeba_D.tar'
else:
    D = DGWGAN(3)
    path_G = './improvedGAN/celeba_G.tar'
    path_D = './improvedGAN/celeba_D.tar'

**Comment by SCccc21** [comment]
Sure. I'll upload to google drive and share the link.

**Comment by AllenPeng-libra** [comment]
when I run recovery.py, the prior loss remains 0，attack acc remains 0，the contribution seems not optimized. Is there a bug？



---Original---
From: "Si ***@***.***&gt;
Date: Thu, Nov 4, 2021 06:37 AM
To: ***@***.***&gt;;
Cc: "Allen ***@***.******@***.***&gt;;
Subject: Re: [SCccc21/Knowledge-Enriched-DMI] weights files (Issue #2)




 
Sure. I'll upload to google drive and share the link.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AllenPeng-libra** [comment]
When I run recovery.py:
[2021-11-03 21:14:02,708 INFO recovery.py line 46 2169] => creating model ...
=> Using improved GAN: True
[2021-11-03 21:14:06,987 INFO recovery.py line 92 2169] => Begin attacking ...
--------------------- Attack batch [0]------------------------------
Iteration:300	Prior Loss:0.00	Iden Loss:14.97	Attack Acc:0.00
Iteration:600	Prior Loss:0.00	Iden Loss:14.90	Attack Acc:0.00
Iteration:900	Prior Loss:0.00	Iden Loss:14.87	Attack Acc:0.00
Iteration:1200	Prior Loss:0.00	Iden Loss:14.85	Attack Acc:0.00
Iteration:1500	Prior Loss:0.00	Iden Loss:14.84	Attack Acc:0.00
Iteration:1800	Prior Loss:0.00	Iden Loss:14.84	Attack Acc:0.00

Is there a bug?? the distrbution seems not optimized.

**Comment by SCccc21** [comment]
Please test with the pretrained GAN models (https://drive.google.com/file/d/1Yr5oQSGbUmSVu9YhWV8BssSqlbey9gRE/view?usp=sharing) and see if this error still exists.

**Comment by AllenPeng-libra** [comment]
You've only uploaded the improved_celeba_G_IR152.tar, no D found?
Could you pls upload improved G and D on vgg16?

**Comment by SCccc21** [comment]
Sorry I shared the wrong link. Please check this one https://drive.google.com/drive/folders/1L3frX-CE4j36pe5vVWuy3SgKGS9kkA70?usp=sharing

**Comment by AllenPeng-libra** [comment]
Still does not work(improved GAN on vgg16)
allen@allen-Erazer-X310:~/peng/code/MID/Knowledge-Enriched-DMI$ python recovery.py 
[2021-11-06 10:13:00,127 INFO recovery.py line 45 4049] Namespace(device='0', dist_flag=False, improved_flag=True, model='VGG16')
[2021-11-06 10:13:00,127 INFO recovery.py line 46 4049] => creating model ...
=> Using improved GAN: True
[2021-11-06 10:13:04,116 INFO recovery.py line 92 4049] => Begin attacking ...
--------------------- Attack batch [0]------------------------------
Iteration:300	Prior Loss:0.00	Iden Loss:15.15	Attack Acc:0.00
Iteration:600	Prior Loss:0.00	Iden Loss:15.08	Attack Acc:0.00
Iteration:900	Prior Loss:0.00	Iden Loss:15.05	Attack Acc:0.00
Iteration:1200	Prior Loss:0.00	Iden Loss:15.04	Attack Acc:0.00
Iteration:1500	Prior Loss:0.00	Iden Loss:15.03	Attack Acc:0.00
Iteration:1800	Prior Loss:0.00	Iden Loss:15.03	Attack Acc:0.00


allen@allen-Erazer-X310:~/peng/code/MID/Knowledge-Enriched-DMI$ python recovery.py 
[2021-11-06 10:16:34,400 INFO recovery.py line 45 4954] Namespace(device='0', dist_flag=True, improved_flag=True, model='VGG16')
[2021-11-06 10:16:34,400 INFO recovery.py line 46 4954] => creating model ...
=> Using improved GAN: True
[2021-11-06 10:16:38,356 INFO recovery.py line 92 4954] => Begin attacking ...
--------------------- Attack batch [0]------------------------------
Iteration:300	Prior Loss:0.00	Iden Loss:14.95	Attack Acc:0.00
Iteration:600	Prior Loss:0.00	Iden Loss:13.32	Attack Acc:0.00
Iteration:900	Prior Loss:0.00	Iden Loss:11.94	Attack Acc:0.00
Iteration:1200	Prior Loss:0.00	Iden Loss:11.22	Attack Acc:0.00
Iteration:1500	Prior Loss:0.00	Iden Loss:10.81	Attack Acc:0.00
Iteration:1800	Prior Loss:0.00	Iden Loss:10.55	Attack Acc:0.00
Iteration:2100	Prior Loss:0.00	Iden Loss:10.36	Attack Acc:0.00

**Comment by AllenPeng-libra** [comment]
Could you please share the evaluation classifiers for the following datasets?
MNIST, chestx-ray8, CIFAR10

**Comment by AllenPeng-libra** [comment]
Could you please share the evaluation classifiers for the following datasets?
MNIST, chestx-ray8, CIFAR10
